pull_request_rules:
  - name: request review
    conditions:
      - base=develop
      - author=renovate[bot]
      - label=dependencies
      - "#approved-reviews-by=0"
      - -merged
      - -closed
    actions:
      request_reviews:
        users:
          - jsec

  - name: queue approved renovate PRs
    conditions:
      - base=develop
      - author=renovate[bot]
      - label=dependencies
      - approved-reviews-by=jsec
      - -merged
      - -closed
      - check-success=renovate/stability-days
      - check-success=security/snyk (jsec)
    actions:
      queue:
        name: Renovate PRs

queue_rules:
  - name: Renovate PRs
    merge_method: squash
    update_method: rebase
    batch_size: 5
    conditions:
      - base=develop
      - -conflict
      - check-success=renovate/stability-days
      - check-success=security/snyk (jsec)
