queue_rules:
  - name: Renovate PRs
    merge_method: squash
    update_method: rebase
    batch_size: 10
    autoqueue: true
    queue_conditions:
      - and:
          - label = dependencies
    branch_protection_injection_mode: merge
