packages:
  - "apps/*"
  - "packages/*"
  - "db"

allowBuilds:
  esbuild: true
  unrs-resolver: true
  lightningcss: true

catalog:
  "@jarsec/eslint-config": 7.2.1
  "@types/node": ^26
  eslint: ^10.3.0
  typescript: 6.0.3
  zod: ^4.3.6
