packages:
  - apps/*
  - packages/*

catalog:
  typescript: 5.9.3
  zod: ^4.3.6
  "@types/node": "^24.10.4"

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - protobufjs
  - unrs-resolver
