/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Circuits = {
    alt: null | number;
    country: null | string;
    id: number;
    lat: null | Numeric;
    lng: null | Numeric;
    location: null | string;
    name: string;
    ref: string;
    url: string;
};

export type ConstructorResults = {
    constructorId: number;
    id: number;
    points: null | Numeric;
    raceId: number;
    status: null | string;
};

export type Constructors = {
    id: number;
    name: string;
    nationality: null | string;
    ref: string;
    url: string;
};

export type ConstructorStandings = {
    constructorId: number;
    id: number;
    points: Numeric;
    position: null | number;
    posText: null | string;
    raceId: number;
    wins: Generated<number>;
};

export type DB = {
    circuits: Circuits;
    constructorResults: ConstructorResults;
    constructors: Constructors;
    constructorStandings: ConstructorStandings;
    drivers: Drivers;
    driverStandings: DriverStandings;
    gooseDbVersion: GooseDbVersion;
    lapTimes: LapTimes;
    pitStops: PitStops;
    qualifying: Qualifying;
    races: Races;
    results: Results;
    seasons: Seasons;
    sprintResults: SprintResults;
    status: Status;
};

export type Drivers = {
    code: null | string;
    dateOfBirth: null | Timestamp;
    firstName: Generated<string>;
    id: number;
    lastName: Generated<string>;
    nationality: null | string;
    number: null | number;
    ref: Generated<string>;
    url: string;
};

export type DriverStandings = {
    driverId: number;
    id: number;
    points: Generated<Numeric>;
    position: null | number;
    posText: null | string;
    raceId: number;
    wins: Generated<null | number>;
};

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type GooseDbVersion = {
    id: Generated<number>;
    isApplied: boolean;
    tstamp: Generated<null | Timestamp>;
    versionId: Int8;
};

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type LapTimes = {
    driverId: number;
    lap: number;
    milliseconds: null | number;
    position: null | number;
    raceId: number;
    time: null | string;
};

export type Numeric = ColumnType<string, number | string, number | string>;

export type PitStops = {
    driverId: number;
    duration: null | string;
    lap: number;
    milliseconds: null | number;
    raceId: number;
    stop: number;
    time: string;
};

export type Qualifying = {
    constructorId: number;
    driverId: number;
    id: number;
    number: Generated<number>;
    position: null | number;
    q1: null | string;
    q2: null | string;
    q3: null | string;
    raceId: number;
};

export type Races = {
    circuitId: number;
    date: Timestamp;
    fp1Date: null | Timestamp;
    fp1Time: null | string;
    fp2Date: null | Timestamp;
    fp2Time: null | string;
    fp3Date: null | Timestamp;
    fp3Time: null | string;
    id: number;
    name: Generated<string>;
    qualiDate: null | Timestamp;
    qualiTime: null | string;
    round: Generated<number>;
    sprintDate: null | Timestamp;
    sprintTime: null | string;
    time: null | string;
    url: null | string;
    year: number;
};

export type Results = {
    constructorId: number;
    driverId: number;
    fastestLap: null | number;
    fastestLapSpeed: null | string;
    fastestLapTime: null | string;
    grid: Generated<number>;
    id: number;
    laps: Generated<number>;
    milliseconds: null | number;
    number: null | number;
    points: Generated<Numeric>;
    position: null | number;
    posOrder: Generated<number>;
    posText: Generated<string>;
    raceId: number;
    rank: Generated<null | number>;
    statusId: null | number;
    time: null | string;
};

export type Seasons = {
    url: string;
    year: number;
};

export type SprintResults = {
    constructorId: number;
    driverId: number;
    fastestLap: null | number;
    fastestLapTime: null | string;
    grid: Generated<number>;
    id: number;
    laps: Generated<number>;
    milliseconds: null | number;
    number: Generated<number>;
    points: Generated<Numeric>;
    position: null | number;
    posOrder: Generated<number>;
    posText: Generated<string>;
    raceId: number;
    statusId: null | number;
    time: null | string;
};

export type Status = {
    id: number;
    status: Generated<string>;
};

export type Timestamp = ColumnType<Date, Date | string, Date | string>;
