create table effone.circuits (
    circuit_id text primary key,
    circuit_name text not null,
    circuit_full_name text not null,
    previous_names text,
    circuit_type text not null check (circuit_type in ('RACE', 'ROAD', 'STREET')),
    direction text not null,
    location text not null,
    country_id text not null,
    country text not null,
    latitude numeric(10, 6) not null,
    longitude numeric(10, 6) not null,
    length_km numeric(6, 3) not null,
    turns integer not null,
    race_count integer not null default 0,
    first_race_id integer,
    first_race_name text,
    first_race_date date,
    last_race_id integer,
    last_race_name text,
    last_race_date date,
    refresh_id bigint not null references effone.refresh_runs(refresh_id)
);

create table effone.constructors (
    constructor_id text primary key,
    constructor_name text not null,
    constructor_full_name text not null,
    country_id text not null,
    nationality text not null,
    entry_count integer not null default 0,
    start_count integer not null default 0,
    race_entry_count integer not null default 0,
    sprint_entry_count integer not null default 0,
    race_start_count integer not null default 0,
    sprint_start_count integer not null default 0,
    win_count integer not null default 0,
    podium_count integer not null default 0,
    fastest_lap_count integer not null default 0,
    qualifying_entry_count integer not null default 0,
    qualifying_p1_count integer not null default 0,
    championship_count integer not null default 0,
    total_points numeric(8, 2) not null default 0,
    total_points_x100 integer not null default 0,
    first_race_id integer,
    first_race_name text,
    first_race_date date,
    last_race_id integer,
    last_race_name text,
    last_race_date date,
    refresh_id bigint not null references effone.refresh_runs(refresh_id)
);

create table effone.drivers (
    driver_id text primary key,
    driver_code text not null,
    driver_number integer,
    first_name text not null,
    last_name text not null,
    driver_name text not null,
    driver_full_name text not null,
    gender text not null check (gender in ('MALE', 'FEMALE')),
    date_of_birth date not null,
    date_of_death date,
    place_of_birth text not null,
    country_of_birth_id text not null,
    nationality_country_id text not null,
    nationality text not null,
    second_nationality_country_id text,
    entry_count integer not null default 0,
    start_count integer not null default 0,
    race_entry_count integer not null default 0,
    sprint_entry_count integer not null default 0,
    race_start_count integer not null default 0,
    sprint_start_count integer not null default 0,
    win_count integer not null default 0,
    podium_count integer not null default 0,
    fastest_lap_count integer not null default 0,
    qualifying_entry_count integer not null default 0,
    qualifying_p1_count integer not null default 0,
    championship_count integer not null default 0,
    total_points numeric(8, 2) not null default 0,
    total_points_x100 integer not null default 0,
    first_race_id integer,
    first_race_name text,
    first_race_date date,
    last_race_id integer,
    last_race_name text,
    last_race_date date,
    refresh_id bigint not null references effone.refresh_runs(refresh_id)
);

create table effone.seasons (
    season integer primary key,
    race_count integer not null default 0,
    sprint_count integer not null default 0,
    driver_count integer not null default 0,
    constructor_count integer not null default 0,
    first_race_date date,
    last_race_date date,
    wdc_driver_id text references effone.drivers(driver_id),
    wdc_driver_name text,
    wcc_constructor_id text references effone.constructors(constructor_id),
    wcc_constructor_name text,
    refresh_id bigint not null references effone.refresh_runs(refresh_id)
);

create table effone.races (
    race_id integer primary key,
    season integer not null references effone.seasons(season),
    race_round integer not null,
    race_name text not null,
    race_official_name text not null,
    race_date date not null,
    race_time time,
    grand_prix_id text not null,
    grand_prix_name text not null,
    circuit_id text not null references effone.circuits(circuit_id),
    circuit_layout_id text not null,
    circuit_type text not null,
    direction text not null,
    course_length_km numeric(6, 3) not null,
    turns integer not null,
    scheduled_laps integer,
    scheduled_distance_km numeric(6, 3),
    race_laps integer not null,
    race_distance_km numeric(6, 3) not null,
    qualifying_format text not null,
    sprint_qualifying_format text,
    fp1_date date,
    fp1_time time,
    fp2_date date,
    fp2_time time,
    fp3_date date,
    fp3_time time,
    qualifying_date date,
    qualifying_time time,
    sprint_qualifying_date date,
    sprint_qualifying_time time,
    sprint_date date,
    sprint_time time,
    winner_driver_id text references effone.drivers(driver_id),
    winner_driver_name text,
    winner_constructor_id text references effone.constructors(constructor_id),
    winner_constructor_name text,
    pole_driver_id text references effone.drivers(driver_id),
    pole_driver_name text,
    sprint_winner_driver_id text references effone.drivers(driver_id),
    sprint_winner_driver_name text,
    sprint_winner_constructor_id text references effone.constructors(constructor_id),
    sprint_winner_constructor_name text,
    refresh_id bigint not null references effone.refresh_runs(refresh_id),
    unique (season, race_round)
);
