create table effone.race_results (
    season integer not null references effone.seasons(season),
    race_round integer not null,
    race_id integer not null references effone.races(race_id),
    race_name text not null,
    race_date date not null,
    circuit_id text not null references effone.circuits(circuit_id),
    driver_id text not null references effone.drivers(driver_id),
    driver_name text not null,
    driver_code text not null,
    constructor_id text not null references effone.constructors(constructor_id),
    constructor_name text not null,
    engine_manufacturer_id text not null,
    tyre_manufacturer_id text not null,
    car_number integer,
    grid_position integer,
    qualifying_position integer,
    finish_position integer,
    finish_order integer not null,
    position_text text not null,
    positions_gained integer,
    points numeric(8, 2) not null default 0,
    points_x100 integer not null default 0,
    laps_completed integer,
    elapsed_time text,
    elapsed_time_ms integer,
    time_penalty text,
    time_penalty_ms integer,
    gap text,
    gap_ms integer,
    gap_laps integer,
    interval text,
    interval_ms integer,
    pit_stop_count integer,
    status text,
    status_category text not null check (
        status_category in (
            'finished',
            'classified_lapped',
            'accident',
            'collision',
            'mechanical',
            'driver_error',
            'disqualified',
            'not_qualified',
            'not_classified',
            'withdrawn',
            'other_retirement',
            'unknown'
        )
    ),
    is_entry boolean not null default true,
    is_start boolean not null,
    is_dnf boolean not null,
    is_classified_finish boolean not null,
    is_win boolean not null,
    is_podium boolean not null,
    is_points_finish boolean not null,
    is_grid_p1 boolean not null,
    is_pole_position boolean not null,
    is_fastest_lap boolean not null,
    is_driver_of_the_day boolean not null,
    is_grand_slam boolean not null,
    refresh_id bigint not null references effone.refresh_runs(refresh_id),
    primary key (race_id, driver_id)
);

create table effone.sprint_results (
    season integer not null references effone.seasons(season),
    race_round integer not null,
    race_id integer not null references effone.races(race_id),
    race_name text not null,
    race_date date not null,
    circuit_id text not null references effone.circuits(circuit_id),
    driver_id text not null references effone.drivers(driver_id),
    driver_name text not null,
    driver_code text not null,
    constructor_id text not null references effone.constructors(constructor_id),
    constructor_name text not null,
    engine_manufacturer_id text not null,
    tyre_manufacturer_id text not null,
    car_number integer,
    grid_position integer,
    qualifying_position integer,
    finish_position integer,
    finish_order integer not null,
    position_text text not null,
    positions_gained integer,
    points numeric(8, 2) not null default 0,
    points_x100 integer not null default 0,
    laps_completed integer,
    elapsed_time text,
    elapsed_time_ms integer,
    time_penalty text,
    time_penalty_ms integer,
    gap text,
    gap_ms integer,
    gap_laps integer,
    interval text,
    interval_ms integer,
    status text,
    status_category text not null check (
        status_category in (
            'finished',
            'classified_lapped',
            'accident',
            'collision',
            'mechanical',
            'driver_error',
            'disqualified',
            'not_qualified',
            'not_classified',
            'withdrawn',
            'other_retirement',
            'unknown'
        )
    ),
    is_entry boolean not null default true,
    is_start boolean not null,
    is_dnf boolean not null,
    is_classified_finish boolean not null,
    is_win boolean not null,
    is_podium boolean not null,
    is_points_finish boolean not null,
    is_grid_p1 boolean not null,
    refresh_id bigint not null references effone.refresh_runs(refresh_id),
    primary key (race_id, driver_id)
);

create table effone.qualifying_results (
    season integer not null references effone.seasons(season),
    race_round integer not null,
    race_id integer not null references effone.races(race_id),
    race_name text not null,
    race_date date not null,
    circuit_id text not null references effone.circuits(circuit_id),
    driver_id text not null references effone.drivers(driver_id),
    driver_name text not null,
    driver_code text not null,
    constructor_id text not null references effone.constructors(constructor_id),
    constructor_name text not null,
    engine_manufacturer_id text not null,
    tyre_manufacturer_id text not null,
    car_number integer,
    qualifying_position integer,
    position_text text not null,
    q1 text,
    q1_ms integer,
    q2 text,
    q2_ms integer,
    q3 text,
    q3_ms integer,
    best_qualifying_time text,
    best_qualifying_ms integer,
    gap text,
    gap_ms integer,
    interval text,
    interval_ms integer,
    laps integer,
    is_entry boolean not null default true,
    is_qualifying_p1 boolean not null,
    advanced_to_q2 boolean not null,
    advanced_to_q3 boolean not null,
    refresh_id bigint not null references effone.refresh_runs(refresh_id),
    primary key (race_id, driver_id)
);

create table effone.fastest_laps (
    season integer not null references effone.seasons(season),
    race_round integer not null,
    race_id integer not null references effone.races(race_id),
    race_name text not null,
    race_date date not null,
    circuit_id text not null references effone.circuits(circuit_id),
    driver_id text not null references effone.drivers(driver_id),
    driver_name text not null,
    driver_code text not null,
    constructor_id text not null references effone.constructors(constructor_id),
    constructor_name text not null,
    engine_manufacturer_id text not null,
    tyre_manufacturer_id text not null,
    car_number integer,
    fastest_lap_order integer not null,
    fastest_lap_position integer,
    position_text text not null,
    lap_number integer,
    lap_time text,
    lap_time_ms integer,
    gap text,
    gap_ms integer,
    interval text,
    interval_ms integer,
    refresh_id bigint not null references effone.refresh_runs(refresh_id),
    primary key (race_id, driver_id)
);

create table effone.pit_stops (
    season integer not null references effone.seasons(season),
    race_round integer not null,
    race_id integer not null references effone.races(race_id),
    race_name text not null,
    race_date date not null,
    circuit_id text not null references effone.circuits(circuit_id),
    driver_id text not null references effone.drivers(driver_id),
    driver_name text not null,
    driver_code text not null,
    constructor_id text not null references effone.constructors(constructor_id),
    constructor_name text not null,
    engine_manufacturer_id text not null,
    tyre_manufacturer_id text not null,
    car_number integer,
    stop_number integer not null,
    lap_number integer not null,
    stop_order integer not null,
    stop_position integer,
    position_text text not null,
    duration text,
    duration_ms integer,
    refresh_id bigint not null references effone.refresh_runs(refresh_id),
    primary key (race_id, driver_id, stop_number)
);

create table effone.driver_standings_snapshots (
    season integer not null references effone.seasons(season),
    race_round integer not null,
    race_id integer not null references effone.races(race_id),
    driver_id text not null references effone.drivers(driver_id),
    driver_name text not null,
    driver_code text not null,
    points numeric(8, 2) not null default 0,
    points_x100 integer not null default 0,
    previous_points numeric(8, 2),
    previous_points_x100 integer,
    points_gained numeric(8, 2),
    points_gained_x100 integer,
    position integer,
    position_text text not null,
    previous_position integer,
    position_change integer,
    championship_won boolean not null default false,
    refresh_id bigint not null references effone.refresh_runs(refresh_id),
    primary key (race_id, driver_id)
);

create table effone.constructor_standings_snapshots (
    season integer not null references effone.seasons(season),
    race_round integer not null,
    race_id integer not null references effone.races(race_id),
    constructor_id text not null references effone.constructors(constructor_id),
    constructor_name text not null,
    engine_manufacturer_id text not null,
    points numeric(8, 2) not null default 0,
    points_x100 integer not null default 0,
    previous_points numeric(8, 2),
    previous_points_x100 integer,
    points_gained numeric(8, 2),
    points_gained_x100 integer,
    position integer,
    position_text text not null,
    previous_position integer,
    position_change integer,
    championship_won boolean not null default false,
    refresh_id bigint not null references effone.refresh_runs(refresh_id),
    primary key (race_id, constructor_id, engine_manufacturer_id)
);

comment on table effone.fastest_laps is 'Fastest-lap ranking facts from the F1DB fastest_lap view. F1DB PostgreSQL dump does not contain full lap-by-lap timings.';
comment on column effone.race_results.finish_order is 'Official result ordering from F1DB position_display_order; use for wins, podiums, and result sorting.';
comment on column effone.race_results.status_category is 'Derived from F1DB reason_retired and result fields; F1DB does not provide a separate status table.';
